kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: iexdemo
    type: nginx
    site: ng1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
