---
apiVersion: v1
kind: Service
metadata:
  name: elastic-service
  labels:
    app: iexdemo
    db: elastic
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 49200
      targetPort: 9200
    - name: transport
      protocol: TCP
      port: 49300
      targetPort: 9300
  clusterIP: 10.10.0.50
  selector:
    app: iexdemo
    db: elastic
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esc-01
  labels:
    app: iexdemo
    db: elastic
spec:
  serviceName: elastic-service
  replicas: 1
  selector:
    matchLabels:
      app: iexdemo
      db: elastic
  template:
    metadata:
      labels:
        app: iexdemo
        db: elastic 
    spec:
      initContainers: #will always initialize before other containers
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es-container
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        env:  
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "es01"
        - name: "ELASTIC_PASSWORD"
          value: "notasecret"
        - name: "DISCOVERY_SERVICE"
          value: "elasticsearch"
        - name: "HTTP_ENABLE"
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
          - name: elastic-data
            mountPath: /data
      volumes:
        - name: elastic-data
          persistentVolumeClaim:
            claimName: elastic-claim
